version: '3.8'

services:
  # 1. BAZA DANYCH
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: energy_db
    ports:
      - "5432:5432" # Dostęp do bazy z poziomu Windowsa
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. BACKEND
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Kluczowe: 'db' to nazwa serwisu zdefiniowana wyżej
      DATABASE_URL: postgresql://admin:password123@db:5432/energy_db
      SECRET_KEY: "super_tajny_klucz_do_jwt"
      # Opcjonalnie dane do maila, jeśli chcesz żeby działały w Dockerze:
      MAIL_USERNAME: energy.app001@gmail.com
      MAIL_PASSWORD: cyxbfsgsulzrvblb
      MAIL_FROM: energy.app001@gmail.com
      MAIL_PORT: 587
      MAIL_SERVER: smtp.gmail.com

  # 3. FRONTEND
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80" # Mapujemy port 3000 Twojego komputera na 80 w kontenerze
    depends_on:
      - backend

volumes:
  postgres_data: