"""Add materials table

Revision ID: 1228300418bf
Revises: 50e3a7a1197e
Create Date: 2026-01-22 19:38:30.147759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1228300418bf'
down_revision: Union[str, Sequence[str], None] = '50e3a7a1197e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('building_parameters_wall_type_id_fkey'), 'building_parameters', type_='foreignkey')
    op.drop_constraint(op.f('building_parameters_roof_type_id_fkey'), 'building_parameters', type_='foreignkey')
    op.drop_constraint(op.f('building_parameters_window_type_id_fkey'), 'building_parameters', type_='foreignkey')
    op.drop_table('material_presets')
    op.create_foreign_key(None, 'building_parameters', 'materials', ['wall_type_id'], ['id'])
    op.create_foreign_key(None, 'building_parameters', 'materials', ['window_type_id'], ['id'])
    op.create_foreign_key(None, 'building_parameters', 'materials', ['roof_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'building_parameters', type_='foreignkey')
    op.drop_constraint(None, 'building_parameters', type_='foreignkey')
    op.drop_constraint(None, 'building_parameters', type_='foreignkey')
    op.create_foreign_key(op.f('building_parameters_window_type_id_fkey'), 'building_parameters', 'material_presets', ['window_type_id'], ['id'])
    op.create_foreign_key(op.f('building_parameters_roof_type_id_fkey'), 'building_parameters', 'material_presets', ['roof_type_id'], ['id'])
    op.create_foreign_key(op.f('building_parameters_wall_type_id_fkey'), 'building_parameters', 'material_presets', ['wall_type_id'], ['id'])
    op.create_table('material_presets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('u_value', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('material_presets_pkey'))
    )
    # ### end Alembic commands ###
