"""Add saved_data to buildings

Revision ID: 50e3a7a1197e
Revises: 94280fe3290d
Create Date: 2026-01-21 21:08:19.378988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e3a7a1197e'
down_revision: Union[str, Sequence[str], None] = '94280fe3290d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('buildings', sa.Column('name', sa.String(), nullable=False))
    op.add_column('buildings', sa.Column('building_type', sa.String(), nullable=True))
    op.add_column('buildings', sa.Column('construction_year', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('floor_area', sa.Float(), nullable=False))
    op.add_column('buildings', sa.Column('city', sa.String(), nullable=True))
    op.add_column('buildings', sa.Column('saved_data', sa.JSON(), nullable=True))
    op.add_column('buildings', sa.Column('calculated_eu', sa.Float(), nullable=True))
    op.add_column('buildings', sa.Column('calculated_ep', sa.Float(), nullable=True))
    op.add_column('buildings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('buildings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.drop_constraint(op.f('buildings_user_id_fkey'), 'buildings', type_='foreignkey')
    op.create_foreign_key(None, 'buildings', 'users', ['owner_id'], ['id'])
    op.drop_column('buildings', 'zone')
    op.drop_column('buildings', 'location')
    op.drop_column('buildings', 'user_id')
    op.drop_column('buildings', 'floors')
    op.drop_column('buildings', 'heated_area')
    op.drop_column('buildings', 'build_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('build_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('buildings', sa.Column('heated_area', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('buildings', sa.Column('floors', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('buildings', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('buildings', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('buildings', sa.Column('zone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'buildings', type_='foreignkey')
    op.create_foreign_key(op.f('buildings_user_id_fkey'), 'buildings', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_column('buildings', 'updated_at')
    op.drop_column('buildings', 'created_at')
    op.drop_column('buildings', 'calculated_ep')
    op.drop_column('buildings', 'calculated_eu')
    op.drop_column('buildings', 'saved_data')
    op.drop_column('buildings', 'city')
    op.drop_column('buildings', 'floor_area')
    op.drop_column('buildings', 'construction_year')
    op.drop_column('buildings', 'building_type')
    op.drop_column('buildings', 'name')
    op.drop_column('buildings', 'owner_id')
    # ### end Alembic commands ###
