"""Add all tables

Revision ID: d47fc14ede26
Revises: 023912d44d6d
Create Date: 2025-12-01 00:43:03.220075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47fc14ede26'
down_revision: Union[str, Sequence[str], None] = '023912d44d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heating_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('efficiency', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('u_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('heated_area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('wall_type_id', sa.Integer(), nullable=True),
    sa.Column('roof_type_id', sa.Integer(), nullable=True),
    sa.Column('window_type_id', sa.Integer(), nullable=True),
    sa.Column('heating_system_id', sa.Integer(), nullable=True),
    sa.Column('ventilation_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['heating_system_id'], ['heating_systems.id'], ),
    sa.ForeignKeyConstraint(['roof_type_id'], ['material_presets.id'], ),
    sa.ForeignKeyConstraint(['wall_type_id'], ['material_presets.id'], ),
    sa.ForeignKeyConstraint(['window_type_id'], ['material_presets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('ep', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ek', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eu', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculations')
    op.drop_table('building_parameters')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('material_presets')
    op.drop_table('heating_systems')
    # ### end Alembic commands ###
