"""Add advanced audits table

Revision ID: e5174f6521a1
Revises: 1228300418bf
Create Date: 2026-01-22 22:03:46.383166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5174f6521a1'
down_revision: Union[str, Sequence[str], None] = '1228300418bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advanced_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('ep_value', sa.Float(), nullable=True),
    sa.Column('ek_value', sa.Float(), nullable=True),
    sa.Column('eu_value', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('passed_wt2021', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advanced_audits_id'), 'advanced_audits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advanced_audits_id'), table_name='advanced_audits')
    op.drop_table('advanced_audits')
    # ### end Alembic commands ###
